// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cc': string;
  'color': string;
  'red': string;
}
export const cssExports: CssExports;
export default cssExports;
